name: CrushFTP10

env:
      TAG: "crushftp10.7.1.43"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
         
      run: docker build . --file .github/workflows/Dockerfile --tag $TAG     

            
