name: Docker Image CrushFTP10

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      
      run:
      
       - unzip CrushFTP/CrushFTP10.zip -d build/
       - docker build . --file .github/workflows/Dockerfile --tag my-image-name:$(date +%s)

            
